import type { DriftReport, DriftLevel } from '@ordomesh/drift-engine'

function levelEmoji(level: DriftLevel): string {
  switch (level) {
    case 'CRITICAL': return '🔴 CRITICAL'
    case 'High':     return '🟠 High'
    case 'Med':      return '🟡 Med'
    case 'Low':      return '🟢 Low'
  }
}

/**
 * Renders a DriftReport as GitHub-flavoured Markdown.
 *
 * Designed to be posted as a PR comment via a GitHub Action:
 *   drift-check --markdown >> $GITHUB_STEP_SUMMARY
 */
export function formatMarkdown(report: DriftReport, topN?: number): string {
  const lines: string[] = []
  const pct = report.overallDriftPct
  const shown = topN ? report.pairs.slice(0, topN) : report.pairs
  const totalActive = report.pairs.length

  const badge =
    pct >= 50 ? '🔴 Critical' :
    pct >= 20 ? '🟡 Degraded' :
                '🟢 Healthy'

  lines.push('## 📊 drift-check Report')
  lines.push('')
  lines.push(`**Total Repository Drift: ${pct}%** — ${badge}`)
  lines.push('')
  lines.push(
    `${totalActive} active code files · ` +
    `${report.pairedFiles} have docs · ` +
    `${report.totalCodeFiles - totalActive} unchanged (excluded)`
  )
  if (topN && totalActive > topN) {
    lines.push(`*Showing top ${topN} of ${totalActive} by drift score.*`)
  }
  lines.push('')
  lines.push('| File | Linked Doc | Drift Level | Stale Metric |')
  lines.push('|------|------------|-------------|--------------|')

  for (const pair of shown) {
    const doc = pair.docFile ? `\`${pair.docFile}\`` : '—'
    const stale =
      pair.docFile === null
        ? 'No documentation found'
        : `${pair.codeCommitCount} commit${pair.codeCommitCount === 1 ? '' : 's'}, doc ${pair.daysSinceDocUpdate}d old`

    lines.push(
      `| \`${pair.codeFile}\` | ${doc} | ${levelEmoji(pair.driftLevel)} | ${stale} |`
    )
  }

  lines.push('')
  lines.push('---')
  lines.push('')
  lines.push(
    '> ⚠️ **Mechanical drift detected.** ' +
    'OrdoMesh can perform a Semantic Audit to verify whether the content ' +
    'of these files actually contradicts your code.'
  )
  lines.push(
    '> Run `drift-check --verify` or visit [ordomesh.com/pilot](https://ordomesh.com/pilot).'
  )
  lines.push('')
  lines.push('*Generated by [drift-check](https://ordomesh.com)*')

  return lines.join('\n') + '\n'
}
