import type { DriftReport, DriftLevel } from '@ordomesh/drift-engine'

function levelLabel(level: DriftLevel): string {
  switch (level) {
    case 'CRITICAL':
      return '🔴 CRITICAL'
    case 'High':
      return '🟠 High'
    case 'Med':
      return '🟡 Med'
    case 'Low':
      return '🟢 Low'
  }
}

/**
 * Renders a DriftReport as reStructuredText (Sphinx-compatible).
 *
 * Designed for Sphinx documentation builds and technical reporting.
 */
export function formatRst(report: DriftReport, topN?: number): string {
  const lines: string[] = []
  const pct = report.overallDriftPct
  const shown = topN ? report.pairs.slice(0, topN) : report.pairs
  const totalActive = report.pairs.length

  const badge =
    pct >= 50 ? '🔴 Critical' : pct >= 20 ? '🟡 Degraded' : '🟢 Healthy'

  // Title
  lines.push('Documentation Drift Report')
  lines.push('='.repeat('Documentation Drift Report'.length))
  lines.push('')

  // Summary section
  lines.push('Summary')
  lines.push('-'.repeat('Summary'.length))
  lines.push('')
  lines.push(`**Total Repository Drift:** ${pct}% — ${badge}`)
  lines.push('')
  lines.push(
    `${totalActive} active code files · ` +
      `${report.pairedFiles} have docs · ` +
      `${report.totalCodeFiles - totalActive} unchanged (excluded)`,
  )
  if (topN && totalActive > topN) {
    lines.push(`*Showing top ${topN} of ${totalActive} by drift score.*`)
  }
  lines.push('')

  // Table header
  lines.push('Drift Details')
  lines.push('-'.repeat('Drift Details'.length))
  lines.push('')

  // Create RST grid table
  const colWidths = [40, 30, 14, 30]
  const topSeparator = '+' + colWidths.map((w) => '-'.repeat(w)).join('+') + '+'
  const headerSeparator =
    '+' + colWidths.map((w) => '='.repeat(w)).join('+') + '+'

  lines.push(topSeparator)
  lines.push(
    '| ' +
      'File'.padEnd(colWidths[0] - 2) +
      ' | ' +
      'Linked Doc'.padEnd(colWidths[1] - 2) +
      ' | ' +
      'Drift Level'.padEnd(colWidths[2] - 2) +
      ' | ' +
      'Stale Metric'.padEnd(colWidths[3] - 2) +
      ' |',
  )
  lines.push(headerSeparator)

  for (const pair of shown) {
    const doc = pair.docFile ? pair.docFile : '—'
    const stale =
      pair.docFile === null
        ? 'No documentation found'
        : `${pair.codeCommitCount} commit${pair.codeCommitCount === 1 ? '' : 's'}, doc ${pair.daysSinceDocUpdate}d old`

    const truncFile =
      pair.codeFile.length > colWidths[0] - 2
        ? '…' + pair.codeFile.slice(-(colWidths[0] - 3))
        : pair.codeFile
    const truncDoc =
      doc.length > colWidths[1] - 2 ? '…' + doc.slice(-(colWidths[1] - 3)) : doc
    const truncStale =
      stale.length > colWidths[3] - 2
        ? stale.slice(0, colWidths[3] - 3) + '…'
        : stale

    lines.push(
      '| ' +
        truncFile.padEnd(colWidths[0] - 2) +
        ' | ' +
        truncDoc.padEnd(colWidths[1] - 2) +
        ' | ' +
        levelLabel(pair.driftLevel).padEnd(colWidths[2] - 2) +
        ' | ' +
        truncStale.padEnd(colWidths[3] - 2) +
        ' |',
    )
    lines.push(topSeparator)
  }
  lines.push('')

  // Notes section
  lines.push('Notes')
  lines.push('-'.repeat('Notes'.length))
  lines.push('')

  if (report.overallDriftPct === 0) {
    lines.push(
      '✅ **All clear!** Your documentation is in sync with your code. Great work maintaining your knowledge base!',
    )
  } else {
    lines.push(
      '⚠️ **Mechanical drift detected.** OrdoMesh can perform a Semantic Audit to verify whether the content of these files actually contradicts your code.',
    )
  }
  lines.push('')
  lines.push('*Generated by* `drift-check` *— visit* `ordomesh.com`_')
  lines.push('')
  lines.push('.. _ordomesh.com: https://ordomesh.com')

  return lines.join('\n') + '\n'
}
